package src.lk.ijse.gdse.util.navigate;

public enum Routes {
DASHBOARD,ACCOUNT,TRANSACTION,BALANCE,REPORT,LOAN,SAVING,CHILD,DEPOSIT,WITHDRAW,ACCTOACC,BALANCECHECK,VIEWCUSTOMERDETAILS,
    LOGIN,GUARDIAN,VIEWACCOUNTDETAILS,VIEWDEPOSIT,VIEWWITHDRAW,LOANCREATE,WORKER,VIEWLOAN,CHILDDEPOSIT,DEPOSITLOAN,WORKERDETAILS;



}
